### PR TITLE
Fix regexes for .fr parsing

### PR DESCRIPTION
**Pull request by Augustin-FL**
pythonwhois currently hang(goes to infinite loop) on any .fr whois parsing. 

image

This happens because of 3 faulty regexes. 
This PR fix the issue and bump the pythonwhois version.

(Related to https://github.com/joepie91/python-whois/issues/156 )

### CODE REVIEW

**Comment by Augustin-FL** [comment]
Hi @kilgoretrout1985, 

Could you please merge this PR & push a new version of this repo to PyPi, if you are ok with the PR content ?

**Comment by kilgoretrout1985** [comment]
Hello, @Augustin-FL, thanks for the PR. Please give me 1-2 days so I will try to check if this PR is not breaking something else.

**Comment by kilgoretrout1985** [comment]
@Augustin-FL, sorry for asking that )) but have you tested your regexp modifications? They do not seem to work on my machine **(same infinite loop)**. Maybe not all modifications got into PR?

I merged your PR into separate branch for now (`fr-tld`). You can install code with your PR like so (not on pypi yet):
```
pip uninstall pythonwhois-alt
pip install https://codeload.github.com/kilgoretrout1985/pythonwhois-alt/zip/refs/heads/fr-tld
```

`./pwhois test.fr` works for you?
test fr

**Comment by Augustin-FL** [comment]
Hi,

Thanks for the heads up (and sorry about that). I just checked and I'm getting the same behavior as you now.
Let me double check and revert back to you 

(In case: I do confirm I tested my code)

**Comment by kilgoretrout1985** [comment]
All I've understood for now:
1) It hangs on test.fr while passing singularity.fr from test-suite.
2) It hangs on regexps from lines 376 and 377 in parse.py (regexp on line 375 is fine).
3) it seems it is somehow connected to optional `(?:address:` match-groups and their quantity.

PS Modification for `changed:` group is fine but it is not enough ((

**Comment by Augustin-FL** [comment]
Hi,

So I was able to concatenate all 3 regexes into a simpler one that doesn't goes to infinite loop

```
nic-hdl:\s*(?P<handle>.+?)\r?\ntype:\s*(?P<type>.+?)\r?\ncontact:\s*(?P<name>.+?)\r?\n(?:address:\s*.+\n)*?(?:country:\s*(?P<country>.+?)\r?\n)?(?:phone:\s*(?P<phone>.+?)\r?\n)?(?:fax-no:\s*(?P<fax>.+?)\r?\n)?(?:.+\n)*?(?:e-mail:\s*(?P<email>.+?)\r?\n)?(?:.+\n)*?.*\n
```

I essentially got rid of the `address` & `changed` fields (which were apparently causing the issue). It seems to work better now:

image

How do you want to proceed? Should I make a new pull request ? (or perhaps should i commit on this branch & let you do a rebase on your side?)

**Comment by kilgoretrout1985** [comment]
@Augustin-FL , thanks for your help! Especially that last note that changed field is actually breaking something and is optional in whois-output.

**I did an alternative regexp that seems to parse more data. Please take a look. Is this ok?**

Planning to release this tomorrow, need some time to update the tests.

```
	# AFNIC madness with country field
	"nic-hdl:\s+(?P<handle>.+)\n" +\
	"type:\s+(?P<type>.+)\n" +\
	"contact:\s+(?P<name>.+)\n" +\
	"(?:.+\n)*?" +\
	"(?:address:\s+(?P<street1>.+)\n" +\
	"address:\s+(?P<street2>.+)\n" +\
	"address:\s+(?P<street3>.+)\n)?" +\
	"country:\s+(?P<country>[A-Za-z]{2,3})\s*\n" +\
	"(?:phone:\s+(?P<phone>.+)\n)?" +\
	"(?:fax-no:\s+(?P<fax>.+)\n)?" +\
	"(?:.+\n)*?" +\
	"(?:e-mail:\s+(?P<email>.+)\n)?" +\
	"(?:.+\n)*?" +\
	"(?:changed:\s+(?P<changedate>[0-9]{4}\-[0-9]{2}\-[0-9]{2}).+\n)?"
```

This regexp outputs:

```
yura@yura-honor16:~/python/pythonwhois-alt$ ./pwhois test.fr
Status            : Active
Registrar         : French Connexion
Registration date : 2003-12-16 23:00:00
Expiration date   : 2025-12-16 23:00:00
Last update       : 2016-10-11 10:20:10
Name server       : edison.coresystem.pro
Name server       : kepler.coresystem.net
Name server       : newton.coresystem.fr
Name server       : thales.coresystem.mobi
Name server       : turing.coresystem.org
E-mail address    : registries@domaine.fr

Registrant
    NIC handle        : FC5283-FRNIC
    Name              : French Connexion
    Country           : France
    E-mail address    : monetises@domaine.fr
    Phone number      : +33.825701700

Technical Contact
    NIC handle        : FC39071-FRNIC
    Name              : French Connexion
    Country           : France
    E-mail address    : monetises@domaine.fr
    Phone number      : +33.825701700

Administrative Contact
    NIC handle        : ANO00-FRNIC
```
```
yura@yura-honor16:~/python/pythonwhois-alt$ ./pwhois ovh.fr
Status            : Active
Registrar         : OVH
Registration date : 1999-11-11 23:00:00
Expiration date   : 2022-11-11 23:00:00
Last update       : 2022-11-03 09:41:22
Name server       : dns.ovh.net
Name server       : dns10.ovh.net
Name server       : ns.ovh.net
Name server       : ns10.ovh.net
E-mail address    : support@ovh.net

Registrant
    NIC handle        : SO255-FRNIC
    Organization      : OVH SAS
    Country           : France
    E-mail address    : oles@ovh.net
    Phone number      : +33.899701761
    Fax number        : +33.320200958

Technical Contact
    NIC handle        : OVH5-FRNIC
    Name              : OVH NET
    Street address    : OVH
                        140, quai du Sartel
    Postal code       : 59100
    City              : Roubaix
    Country           : France
    E-mail address    : tech@ovh.net
    Phone number      : +33.899701761

Administrative Contact
    NIC handle        : OS10535-FRNIC
    Organization      : OVH SAS
    Street address    : OVH SAS
                        2 Rue Kellermann
    Postal code       : 59100
    City              : Roubaix
    Country           : France
    E-mail address    : x4zojgmlpzo8z127ekjs@z.o-w-o.info
    Phone number      : +33.972100908
```
```
yura@yura-honor16:~/python/pythonwhois-alt$ ./pwhois singularity.fr
Status            : Active
Registrar         : Gandi
Registration date : 2009-04-04 19:28:55
Expiration date   : 2023-08-31 22:01:18
Last update       : 2022-11-02 19:10:01
Name server       : ns-pri.toile-libre.org
Name server       : ns-sec.toile-libre.org
E-mail address    : support@support.gandi.net

Registrant
    NIC handle        : ANO00-FRNIC

Technical Contact
    NIC handle        : G768-FRNIC
    Name              : GANDI
    Street address    : GANDI
                        63-65 Boulevard MASSENA
    Postal code       : 75013
    City              : Paris
    Country           : France
    E-mail address    : noc@gandi.net
    Phone number      : +33.143737851
    Fax number        : +33.143731851

Administrative Contact
    NIC handle        : ANO00-FRNIC
```

**Comment by Augustin-FL** [comment]
Hi,

Wow, thanks !

Indeed your regex is better than mine (sorry, i'm not an expert in regexes...). I tested it on some domains aswell, it seems to work flawlessly :)

**Comment by kilgoretrout1985** [comment]
Released new version on pypi.

**Comment by Augustin-FL** [comment]
Thank you !

**Pull request merged**
